.TH SDL_HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION\fR -- Hints

.SH Synopsis
A hint that specifies the Android APK expansion patch file version

.SH DESCRIPTION
Values
.TP 5
.BI X
the Android APK expansion patch file version (should be string number like "1", "2", etc.)

.SH DEFAULT
By default this hint is not set.

.SH REMARKS
This hint must be set together with the hint \fBSDL_HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION\fR
.PP
If both hints were set then \fBSDL_RWFromFile()\fR will look into expansion files after a given relative path was not found in the internal storage and assets.
.PP
By default this hint is not set and the APK expansion files are not searched.

.SH VERSION
Available since SDL 2.0.4.

.SH NOTE
Draft
