.TH SDL_GameControllerMappingForGUID 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GameControllerMappingForGUID\fR -- Function

.SH SYNOPSIS
Use this function to get the game controller mapping string for a given GUID.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
char* SDL_GameControllerMappingForGUID(SDL_JoystickGUID guid)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
guid:T{
a structure containing the GUID for which a mapping is desired
T}
.TE

.SH RETURN VALUE
Returns a mapping string or NULL on error; call \fBSDL_GetError()\fR for more information.

.SH REMARKS
The returned string must be freed with \fBSDL_free()\fR.

.SH RELATED FUNCTIONS
\fISDL_JoystickGetDeviceGUID
.br
\fISDL_JoystickGetGUID
