.TH SDL_HapticNewEffect 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HapticNewEffect\fR -- Function

.SH SYNOPSIS
Use this function to create a new haptic effect on a specified device.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_HapticNewEffect(SDL_Haptic*         haptic,
                        SDL_HapticEffect*   effect)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
haptic:T{
an \fBSDL_Haptic\fR device to create the effect on
T}
effect:T{
an \fBSDL_HapticEffect\fR structure containing the properties of the effect to create
T}
.TE

.SH RETURN VALUE
Returns the ID of the effect on success or a negative error code on failure; call \fBSDL_GetError()\fR for more information.

.SH RELATED FUNCTIONS
\fISDL_HapticDestroyEffect\fR
.br
\fISDL_HapticRunEffect\fR
.br
\fISDL_HapticUpdateEffect\fR
