.TH SDL_Texture 3 "2018.09.27" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_Texture\fR -- Structure

.SH SYNOPSIS
A structure that contains an efficient, driver-specific representation of pixel data.

.SH RELATED FUNCTIONS
\fISDL_CreateTexture
.br
\fISDL_CreateTextureFromSurface
.br
\fISDL_DestroyTexture
.br
\fISDL_GetTextureAlphaMod
.br
\fISDL_GetTextureBlendMode
.br
\fISDL_GetTextureColorMod
.br
\fISDL_LockTexture
.br
\fISDL_QueryTexture
.br
\fISDL_RenderCopy
.br
\fISDL_SetTextureAlphaMod
.br
\fISDL_SetTextureBlendMode
.br
\fISDL_SetTextureColorMod
.br
\fISDL_UnlockTexture
.br
\fISDL_UpdateTexture
