.TH SDL_GetMouseState 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GetMouseState\fR -- Function

.SH SYNOPSIS
Use this function to retrieve the current state of the mouse.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
Uint32 SDL_GetMouseState(int* x
                         int* y)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
x:T{
the x coordinate of the mouse cursor position relative to the focus window
T}
y:T{
the y coordinate of the mouse cursor position relative to the focus window
T}
.TE

.SH RETURN VALUE
Returns a 32-bit button bitmask of the current button state.

.SH CODE EXAMPLES
.TS
tab(:) allbox;
a.
T{
.nf
SDL_PumpEvents();
if (SDL_GetMouseState(NULL, NULL) & SDL_BUTTON(SDL_BUTTON_LEFT)
{
  SDL_Log("Mouse BUtton 1 (left) is pressed.");
}
.fi
T}
.TE

.SH REMARKS
The current button state is returned as a button bitmask, which can be tested using the \fBSDL_BUTTON(X)\fR macros (where X is generally 1 for the left, 2 for middle, 3 for the right button), and \fBx\fR and \fBy\fR are set to the mouse cursor position relative to the focus window for the currently selected mouse. You can pass NULL for either \fBx\fR and \fBy\fR.

.SH RELATED FUNCTIONS
\fISDL_GetGlobalMouseState
.br
\fISDL_GetRelativeMouseState
.br
\fISDL_PumpEvents
