.TH SDL_GetRendererInfo 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GetRendererInfo\fR -- Function

.SH SYNOPSIS
Use this function to get information about a rendering context.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_GetRendererInfo(SDL_Renderer*       renderer,
                        SDL_RendererInfo*   info)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
renderer:T{
the rendering context
T}
info:T{
an \fBSDL_RendererInfo\fR structure filled with information about the current renderer
T}
.TE

.SH RETURN VALUE
Returns 0 on success or a negative error code on failure; call \fBSDL_GetError()\fR fore more information.

.SH RELATED FUNCTIONS
\fISDL_CreateRenderer
