.TH SDL_AudioDeviceEvent 3 "2018.09.27" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_AudioDeviceEvent\fR -- Structure

.SH SYNOPSIS
A structure that containsa Audio device event information.

.SH DATA FIELDS
.TS
tab(:) allbox;
a lb l.
Uint32:type:T{
\fBSDL_AUDIODEVICEDDED\fR, or \fBSDL_AUDIODEVICEREMOVED\fR
T}
Uint32:timestamp:T{
the timestamp of the event
T}
Uint32:which:T{
the audio device index for the \fBSDL_AUDIODEVICEADDED\fR event (valid until next \fBSDL_GetNumAudioDevices()\fR call), \fBSDL_AudioDeviceID\fR for the \fBSDL_AUDIODEVICEREMOVED\fR event
T}
Uint8:iscapture:T{
zero if an audio output device, non-zero if an audio capture device
T}
.TE

.SH VERSIONS
This structure is available since SDL 2.0.4.

.SH RELATED ENUMERATIONS
\fISDL_EventType

.SH RELATED STRUCTURES
\fISDL_Event

.SH RELATED FUNCTIONS
\fISDL_GetNumAudioDevices
