.TH SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT\fR -- Hints

.SH SYNOPSIS
A hint that specifies a value to override the binding element for keyboard inputs for Emscripten builds.

.SH DESCRIPTION
Values
.TP 12
.BI #window
the JavaScript window object \fB(this is the default)
.TP
.BI #document
the JavaScript document object
.TP
.BI #screen
the JavaScript \fBwindow.screen\fR object
.TP
.BI #canvas
the default WebGL canvas element

.PP
Any other string without a leading # sign applies to the element on the page with that ID.

.SH DEFAULT
By default SDL will use the JavaScript window object.

.SH REMARKS
This hint only applies to the Emscripten platform.

.SH VERSION
Available since SDL 2.0.4

.SH NOTE
Draft
