.TH SDL_QuitSubSystem 3 "2021.08.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_QuitSubSystem\fR -- Function

.SH SYNOPSIS
Shut down specific SDL subsystems.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_QuitSubSystem(Uint32 flags)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
flags:T{
any of the flags used by \fBSDL_Init()\fR; see \fBSDL_Init\fR for details
T}
.TE

.SH REMARKS
If you start a subsystem using a call to that subsystem's init function (for example \fBSDL_VideoInit()\fR) instead of \fBSDL_Init()\fR or \fBSDL_InitSubSystem()\fR, \fBSDL_QuitSubSystem()\fR and \fBSDL_WasInit()\fR will not work. You will need to use that subsystem's quit function (\fBSDL_VideoQuit()\fR) directly instead. But generally, you should not be using those functions directly anyhow; use \fBSDL_Init()\fR instead.
.PP
You still need to call \fBSDL_Quit()\fR even if you close all open subsystems with \fBSDL_QuitSubSystem()\fR.


.SH CODE EXAMPLES
.TS
tab(:) allbox;
a.
T{
.nf
#include "SDL.h"

/* ... */

int main(int argc, char **argv) {
    int sdl_initialized = 0;
    sdl_initialized = !SDL_Init(0);

    /* ... console stuff ... */

    if (sdl_initialized && SDL_InitSubSystem(SDL_INIT_VIDEO)) {
        display_graph();
        SDL_QuitSubSystem(SDL_INIT_VIDEO);
    }

    /* ... more console stuff ... */

    if (sdl_initialized) SDL_Quit();
    return 0;
}
.fi
T}
.TE

.SH RELATED FUNCTIONS
\fISDL_InitSubSystem\fR
.br
\fISDL_Quit\fR
