.TH SDL_NumJoysticks 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_NumJoysticks\fR -- Function

.SH SYNOPSIS
Use this function to count the number of joysticks attached to the system.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_NumJoysticks(void)
.fi
T}
.TE

.SH RETURN VALUE
Returns the number of attached joysticks on success or a negative error code on failure; call \fBSDL_GetError()\fR for more information.

.SH RELATED FUNCTIONS
\fISDL_JoystickName
.br
\fISDL_JoystickOpen
