.TH SDL_GetWindowData 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GetWindowData\fR -- Function

.SH SYNOPSIS
Use this function to retrieve the data pointer associated with a window.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void* SDL_GetWindowData(SDL_Window*   window,
                        const char*   name)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
window:T{
the window to query
T}
name:T{
the name of the pointer
T}
.TE

.SH RETURN VALUE
Returns the value associated with \fBname\fR.

.SH RELATED FUNCTIONS
\fISDL_SetWindowData\fR
