.TH SDL_LoadBMP_RW 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_LoadBMP_RW\fR -- Function

.SH SYNOPSIS
Use this function to load a BMP image from a seekable SDL data stream (memory or file).

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
SDL_Surface SDL_LoadBMP_RW(SDL_RWops*   src,
                           int          freesrc)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
src:T{
the data stream for the surface
T}
freesrc:T{
non-zero to close the stream after being read
T}
.TE

.SH RETURN VALUE
Returns a pointer to a new \fBSDL_Surface\fR structure or NULL if there was an error; call \fBSDL_GetError()\fR for more information.

.SH REMARKS
The new surface should be freed with \fBSDL_FreeSurface()\fR.

.SH RELATED FUNCTIONS
\fISDL_FreeSurface\fR
.br
\fISDL_LoadBMP\fR
.br
\fISDL_SaveBMP_RW\fR
