.TH SDL_bool 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_bool\fR -- Enumerations

.SH SYNOPSIS
An enumeration of boolean values.

.SH DESCRIPTION
Values
.TS
tab(:) allbox;
ab l.
SDL_FALSE:T{
value which is equal to 0 or false
T}
SDL_TRUE:T{
value which is equal to 1 or true
T}
.TE

.SH REMARKS
Every function, structure, class etc. will work with SDL_bool.
