.TH SDL_GL_DeleteContext 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GL_DeleteContext\fR -- Function

.SH SYNOPSIS
Use this function to delete an OpenGL context.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_GL_DeleteContext(SDL_GLContext context)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
context:the OpenGL context to be deleted
.TE

.SH RELATED FUNCTIONS
\fISDL_GL_CreateContext
