.TH SDL_LogSetPriority 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_LogSetPriority\fR -- Function

.SH SYNOPSIS
Use this function to set the priority of a particular log category.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_LogSetPriority(int               category,
                        SDL_LogPriority   priority)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
category:T{
the category to assign a priority to; see \fIRemarks\fR for details
T}
priority:T{
the \fBSDL_LogPriority\fR to assign; see \fIRemarks\fR for details
T}
.TE

.SH REMARKS
The \fBcategory\fR will be one of:

.TS
tab(:) allbox;
ab a.
SDL_LOG_CATEGORY_APPLICATION:T{
application log
T}
SDL_LOG_CATEGORY_ERROR:T{
error log
T}
SDL_LOG_CATEGORY_ASSERT:T{
assert log
T}
SDL_LOG_CATEGORY_SYSTEM:T{
system log
T}
SDL_LOG_CATEGORY_AUDIO:T{
audio log
T}
SDL_LOG_CATEGORY_VIDEO:T{
video log
T}
SDL_LOG_CATEGORY_RENDER:T{
render log
T}
SDL_LOG_CATEGORY_INPUT:T{
input log
T}
SDL_LOG_CATEGORY_TEST:T{
test log
T}
SDL_LOG_CATEGORY_RESERVED#:T{
# = 1-10; reserved for future SDL library use
T}
SDL_LOG_CATEGORY_CUSTOM:T{
reserved for application use; see \fIRemarks\fR(\fIhttps://wiki.libsdl.org/SDL_LOG_CATEGORY#Remarks\fR) for details
T}
.TE

The \fBpriority\fR can be one of:

.TS
tab(:) allbox;
ab a.
SDL_LOG_PRIORITY_VERBOSE:
SDL_LOG_PRIORITY_DEBUG:
SDL_LOG_PRIORITY_INFO:
SDL_LOG_PRIORITY_WARN:
SDL_LOG_PRIORITY_ERROR:
SDL_LOG_PRIORITY_CRITICAL:
SDL_NUM_LOG_PRIORITIES:(internal use)
.TE

.SH RELATED FUNCTIONS
\fISDL_LogGetPriority\fR
.br
\fISDL_LogSetAllPriority\fR
