.TH SDL_FreePalette 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_FreePalette\fR -- Function

.SH SYNOPSIS
Use this function to free a palette created with \fBSDL_AllocPalette()\fR.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_FreePalette(SDL_Palette* palette)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
palette:the \fBSDL_Palette\fR structure to be freed
.TE

.SH RELATED FUNCTIONS
\fISDL_AllocPalette
