.TH SDL_SwapBE64 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_SwapBE64\fR -- Function

.SH SYNOPSIS
Use this function to swap the byte order of a 64-bit big-endian value to native ordering.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
Uint64 SDL_SwapBE64(Uint64    x)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
x:T{
the value to be swapped
T}
.TE

.SH RETURN VALUE
Returns the native 64-bit value.

.SH RELATED FUNCTIONS
\fISDL_Swap64\fR
.br
\fISDL_SwapLE64\fR
