.TH SDL_SemWait 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_SemWait\fR -- Function

.SH SYNOPSIS
Use this function to wait until a semaphore has a positive value and then decrements it.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_SemWait(SDL_sem*    sem)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
sem:T{
the semaphore wait on
T}
.TE

.SH RETURN VALUE
Returns 0 on success or a negative error code on failure; call \fBSDL_GetError()\fR for more information.

.SH CODE EXAMPLES
.TS
tab(:) allbox;
a.
T{
.nf
SDL_atomic_t done;
SDL_sem *sem;

SDL_AtomicSet(&done, 0);
sem = SDL_CreateSemaphore(0);
.
.
Thread A:
    while (!SDL_AtomicGet(&done)) {
        add_data_to_queue();
        SDL_SemPost(sem);
    }

Thread B:
    while (!SDL_AtomicGet(&done)) {
        SDL_SemWait(sem);
        if (data_available()) {
            get_data_from_queue();
        }
    }
.
.
SDL_AtomicSet(&done, 1);
SDL_SemPost(sem);
wait_for_threads();
SDL_DestroySemaphore(sem);
.fi
T}
.TE

.SH REMARKS
This function suspends the calling thread until either the semaphore pointed to by \fBsem\fR has a positive value or the call is interrupted by a signal or error. If the call is successful, it will atomically decrement the semaphore value.

This function is the equivalent of calling \fBSDL_SemWaitTimeout()\fR with a time length of \fBSDL_MUTEX_MAXWAIT\fR.

.SH RELATED FUNCTIONS
\fISDL_CreateSemaphore\fR
.br
\fISDL_DestroySemaphore\fR
.br
\fISDL_SemPost\fR
.br
\fISDL_SemTryWait\fR
.br
\fISDL_SemValue\fR
.br
\fISDL_SemWait\fR
.br
\fISDL_SemWaitTimeout\fR
