.TH SDL_GetDefaultCursor 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GetDefaultCursor\fR -- Function

.SH SYNOPSIS
Use this function to get the default cursor.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
SDL_Cursor* SDL_GetDefaultCursor(void)
.fi
T}
.TE

.SH RETURN VALUE
Returns the default cursor on success or NULL on failure.

.SH VERSION
This function is available since SDL 2.0.0.

.SH RELATED FUNCTIONS
\fISDL_CreateSystemCursor
