.TH SDL_SwapFloatLE 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_SwapFloatLE\fR -- Function

.SH SYNOPSIS
Use this function to swap the byte order of a little-endian floating point value to native ordering.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
float SDL_SwapFloatLE(float   x)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
x:T{
the value to be swapped
T}
.TE

.SH RETURN VALUE
Returns the native floating point value.

.SH RELATED FUNCTIONS
\fISDL_SwapFloat\fR
.br
\fISDL_SwapFloatBE\fR
