.TH SDL_Init 3 "2021.08.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
SDL_Init - API

.SH SYNOPSIS
Initialize the SDL library.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_Init(Uint32 flags)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
flags:T{
subsystem initialization flags
T}
.TE

.SH RETURN VALUE
Returns 0 on success or a negative error code on failure; call \fBSDL_GetError()\fR for more information.

.SH REMARKS
\fBSDL_Init\fR() simply forwards to calling \fBSDL_InitSubSystem\fR(). Therefore, the two may be used interchangeably. Though for readability of your code \fBSDL_InitSubSystem\fR() might be preferred.
.PP
The file I/O (for example: \fBSDL_RWFromFile\fR) and threading (\fBSDL_CreateThread\fR) subsystems are initialized by default. Message boxes (\fBSDL_ShowSimpleMessageBox\fR) also attempt to work without initializing the video subsystem, in hopes of being useful in showing an error dialog when \fBSDL_Init\fR fails. You must specifically initialize other subsystems if you use them in your application.
.PP
Logging (such as \fBSDL_Log\fR) works without initialization, too.

.PP
\fBflags\fR may be any of the following OR'd together.
.PP
.RS 4
\fBSDL_INIT_TIMER
\fRtimer subsystem
.br
\fBSDL_INIT_AUDIO
\fRaudio subsystem
.br
\fBSDL_INIT_VIDEO
\fRvideo subsystem; automatically initializes the events subsystem
.br
\fBSDL_INIT_JOYSTICK
\fRjoystick subsystem; automatically initializes the events subsystem
.br
\fBSDL_INIT_HAPTIC
\fRhaptic (force feedback) subsystem
.br
\fBSDL_INIT_GAMECONTROLLER
\fRcontroller subsystem; automatically intitializes the joystick subsystem
.br
\fBSDL_INIT_EVENTS
\fRevents subsytem
.br
\fBSDL_INIT_EVERYTHING
\fRall of the above subsystems
.br
\fBSDL_INIT_NOPARACHUTE
\fRcompatibility; this flag is ignored
.RE

.PP
Subsystem initialization is ref-counted, you must call \fBSDL_QuitSubSystem()\fR for each \fBSDL_InitSubSystem()\fR to correctly shutdown a subsystem manually (or call \fBSDL_Quit()\fR to force shutdown). If a subsystem is already loaded then this call will increase the ref-count and return.

.SH CODE EXAMPLES
.TS
tab(:) allbox;
a.
T{
.nf
#include "SDL.h"

int main(int argc, char* argv[])
{
    if (SDL_Init(SDL_INIT_VIDEO|SDL_INIT_AUDIO) != 0) {
        SDL_Log("Unable to initialize SDL: %s", SDL_GetError());
        return 1;
    }

    /* ... */

    SDL_Quit();

    return 0;
}
T}
.TE

.SH RELATED FUNCTIONS
\fISDL_InitSubSystem\fR
.br
\fISDL_Quit\fR
.br
\fISDL_SetMainReady\fR
.br
\fISDL_WasInit\fR

