.TH SDL_HintPriority 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HintPriority\fR -- Enumerations

.SH SYNOPSIS
An enumeration of hint priorities.

.SH DESCRIPTION
Values
.TS
tab(:) allbox;
ab l.
SDL_HINT_DEFAULT:T{
low priority, used for default values
T}
SDL_HINT_NORMAL:T{
medium priority
T}
SDL_HINT_OVERRIDE:T{
high priority
T}
.TE

.SH RELATED FUNCTIONS
\fISDL_SetHintWithPriority
