.TH SDL_MessageBoxColorScheme 3 "2018.09.27" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_MessageBoxColorScheme\fR -- Structure

.SH SYNOPSIS
A structure that contains a set of colors to use for message box dialogs.

.SH DATA FIELDS
.TS
tab(:) allbox;
a lb l.
\fBSDL_MessageBoxColor[5]\fR:colors:
.TE

.SH RELATED ENUMERATIONS
\fISDL_MessageBoxColorType

.SH RELATED STRUCTURES
\fISDL_MessageBoxColor
.br
\fISDL_MessageBoxData
