.TH SDL_RenderFillRect 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_RenderFillRect\fR -- Function

.SH SYNOPSIS
Use this function to fill a rectangle on the current rendering target with the drawing color.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_RenderFillRect(SDL_Renderer*      renderer,
                       const SDL_Rect*    rect)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
renderer:T{
the rendering context
T}
rect:T{
the \fBSDL_Rect\fR structure representing the rectangle to fill, or NULL for the entire rendering target
T}
.TE

.SH RETURN VALUE
Returns 0 on success or a negative error code on failure; call \fBSDL_GetError()\fR for more information.

.SH REMARKS
The current drawing color is set by \fBSDL_SetRenderDrawColor()\fR, and the color's alpha value is ignored unless blending is enabled with appropriate call to \fBSDL_SetRenderDrawBlendMode()\fR.

.SH RELATED FUNCTIONS
\fISDL_RenderDrawLine\fR
.br
\fISDL_RenderDrawLines\fR
.br
\fISDL_RenderDrawPoint\fR
.br
\fISDL_RenderDrawPoints\fR
.br
\fISDL_RenderDrawRect\fR
.br
\fISDL_RenderDrawRects\fR
.br
\fISDL_RenderFillRects\fR
.br
\fISDL_RenderPresent\fR
.br
\fISDL_SetRenderDrawBlendMode\fR
.br
\fISDL_SetRenderDrawColor\fR
