.TH SDL_HapticCustom 3 "2018.09.27" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HapticCustom\fR -- Structure

.SH SYNOPSIS
A structure that contains a template for the \fBSDL_HAPTIC_CUSTOM\fR (a custom) effect.

.SH DATA FIELDS
.TS
tab(:) allbox;
c s s.
Header
.T&
a lb l.
Uint16:type:T{
\fBSDL_HAPTIC_CUSTOM\fR
T}
\fBSDL_HapticDirection\fR:direction:T{
direction of the effect (relative to the user)
T}
.T&
c s s.
Replay
.T&
a lb l.
Uint32:length:T{
duration of the effect
T}
Uint16:delay:T{
delay before starting the effect
T}
.T&
c s s.
Trigger
.T&
a lb l.
Uint16:button:T{
button that triggers the effect
T}
Uint16:interval:T{
how soon it can be triggered again after \fBbutton\fR
T}
.T&
c s s.
Custom
.T&
a lb l.
Uint8:channels:T{
axes to use, minimum of 1; see \fIRemarks\fR for details
T}
Uint16:period:T{
sample periods
T}
Uint16:samples:T{
amount (number) of samples
T}
Uint16*:data:T{
should contain \fBchannels*samples\fR items; see \fIRemarks\fR for details
T}
.T&
c s s.
Envelope
.T&
a lb l.
Uint16:attack_length:T{
duration of the attack
T}
Uint16:attack_level:T{
level at the start of the attack
T}
Uint16:fade_length:T{
duration of the fade
T}
Uint16:fade_level:T{
level at the end of the fade
T}
.TE

.SH REMARKS
This struct is exclusively for the \fBSDL_HAPTIC_CUSTOM\fR effect.

A custom force feedback effect is much like a periodic effect, where the application can define \fIits\fR exact shape. You will have to allocate the data yourself.

\fBdata\fR should consist of \fBchannels * samples\fR Uint16 samples.

If \fBchannels\fR is 1, the effect is rotated using the defined direction. Otherwise it uses the samples in \fBdata\fR for the different axes.

.SH RELATED STRUCTURES
\fISDL_HapticDirection
.br
\fISDL_HapticEffect

.SH RELATED FUNCTIONS
\fISDL_HapticNewEffect
