.TH SDL_HapticRumbleInit 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HapticRumbleInit\fR -- Function

.SH SYNOPSIS
Use this function to initialize the haptic device for simple rumble playback.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_HapticRumbleInit(SDL_Haptic*    haptic)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
haptic:T{
the haptic device to initialize for simple rumble playback
T}
.TE

.SH RETURN VALUE
Returns 0 on success or a negative error code on failure; call \fBSDL_GetError()\fR for more information.

.SH VERSION
This function is available since SDL 2.0.0.

.SH RELATED FUNCTIONS
\fISDL_HapticOpen\fR
.br
\fISDL_HapticRumblePlay\fR
.br
\fISDL_HapticRumbleStop\fR
.br
\fISDL_HapticRumbleSupported\fR
