.TH SDL_MouseWheelEvent 3 "2018.09.27" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_MouseWheelEvent\fR -- Structure

.SH SYNOPSIS
A structure that contains mouse wheel event information.

.SH DATA FIELDS
.TS
tab(:) allbox;
a lb l.
Uint32:type:T{
\fBSDL_MOUSEWHEEL\fR
T}
Uint32:timestamp:T{
timestamp of the event
T}
Uint32:windowID:T{
the window with mouse focus, if any
T}
Uint32:which:T{
the mouse instance id, or \fBSDL_TOUCH_MOUSEID\fR; see \fIRemarks\fR for details
T}
Sint32:x:T{
the amount scrolled horizontally, positive to the right and negative to the left
T}
Sint32:y:T{
the amount scrolled vertically, positive away from the user and negative toward the uer
T}
Uint32:direction:T{
\fBSDL_MOUSEWHEEL_NORMAL\fR or \fBSDL_MOUSEWHEEL_FLIPPED\fR; see \fIRemarks\fR for details (>= SDL 2.0.4)
T}
.TE

.SH CODE EXAMPLES

.nf
SDL_Event event;
while (SDL_PollEvent(&event))
{
  if (event.type == SDL_MOUSEWHEEL)
  {
    if (event.wheel.y > 0) // scroll up
    {
      // pull up code here!
    }
    else if (event.wheel.y < 0) // scroll down
    {
      // pull down code here!
    }
    else if (event.wheel.x > 0)  // scroll right
    {
      // ...
    }
    else if (event.wheel.x < 0)  // scroll left
    {
      // ...
    }
  }
  else if (event.type == SDL_MOUSEBUTTONDOWN)
  {
    // ... handle mouse clicks ...
  }
  // ... handle other kinds of events ...
}
.fi

.SH REMARKS
\fBSDL_MouseWheelEvent\fR is a member of the \fBSDL_Event\fR union and is used when an event of type \fBSDL_MOUSEWHEEL\fR is reported. You would access it through the event's \fIwheel\fR field.

An \fBSDL_MOUSEWHEEL\fR event occurs whenever a user moves the mouse wheel.

Movements to the left generate negative \fBx\fR values and to the right generate positive \fBx\fR values. Movements down (scroll backward) generate negative \fBy\fR values and up (scroll forward) generate positive \fBy\fR values.

\fBwhich\fR may be \fBSDL_TOUCH_MOUSEID\fR, for events that were generated by a touch input device, and not a real mouse. You might want to ignore such events, if your application already handles \fBSDL_TouchFingerEvent\fR.

SDL does not abstract the mouse wheel scroll directions to be consistent across all platforms (\fBSDL_MOUSEWHEEL_NORMAL\fR). If \fBdirection\fR is \fBSDL_MOUSEWHEEL_FLIPPED\fR the values in \fBx\fR and \fBy\fR will be opposite. Multiply by -1 to change them back.

.SH RELATED ENUMERATIONS
\fISDL_EventType

.SH RELATED STRUCTURES
\fISDL_Event
.br
\fISDL_MouseButtonEvent
.br
\fISDL_MouseMotionEvent
