.TH SDL_UnionRect 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_UnionRect\fR -- Function

.SH SYNOPSIS
Use this function to calculate the union of two rectangles.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_UnionRect(const SDL_Rect*    A,
                   const SDL_Rect*    B,
                   SDL_Rect*          result)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
A:T{
an \fBSDL_Rect\fR structure representing the first rectangle
T}
B:T{
an \fBSDL_Rect\fR structure representing the second rectangle
T}
result:T{
an \fBSDL_Rect\fR structure filled in with the union of rectangle \fBA\fR and \fBB\fR
T}
.TE
