.TH SDL_HideWindow 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HideWindow\fR -- Function

.SH SYNOPSIS
Use this function to hide a window.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_HideWindow(SDL_Window*   window)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
window:T{
the window to hide
T}
.TE

.SH RELATED FUNCTIONS
\fISDL_ShowWindow\fR
