.TH SDL_assert_paranoid 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_assert_paranoid\fR -- Function

.SH SYNOPSIS
Use this function to create an assertion for detailed checking.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_assert_paranoid(condition)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
condition:T{
the expression to check
T}
.TE

.SH REMARKS
This function is disabled by default. It is available for use only when the \fBSDL_ASSERT_LEVEL\fR is set to 3. See the \fIAssertions Category page\fR (\fIhttps://wiki.libsdl.org/CategoryAssertions\fR) for details.

.SH RELATED FUNCTIONS
\fISDL_assert\fR
.br
\fISDL_assert_release\fR
