.TH SDL_SwapLE16 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_SwapLE16\fR -- Function

.SH SYNOPSIS
Use this function to swap the byte order of a 16-bit little-endian value to native ordering.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
Uint16 SDL_SwapLE16(Uint16    x)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
x:T{
the value to be swapped
T}
.TE

.SH RETURN VALUE
Returns the native 16-bit value.

.SH RELATED FUNCTIONS
\fISDL_Swap16\fR
.br
\fISDL_SwapBE16\fR
