.TH SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION\fR -- Hints

.SH SYNOPSIS
A hint that specifies whether the Apple TV remote's joystick axes will automatically match the rotation of the remote.

.SH DESCRIPTION
Values
.TP 5
.BI 0
remote orientation does not affect joystick axes
.TP
.BI 1
joystick axes are based on the orientation of the remote

.SH DEFAULT
By default remote orientation does not affect joystick axes.

.SH VERSION
Available since SDL 2.0.5

.SH NOTE
Draft
