.TH SDL_GameControllerButton 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GameControllerButton\fR -- Enumerations

.SH SYNOPSIS
An enumeration of buttons available from a controller.

.SH DESCRIPTION
Values
.TS
tab(:) allbox;
ab l.
SDL_CONTROLLER_BUTTON_INVALID:--
SDL_CONTROLLER_BUTTON_A:--
SDL_CONTROLLER_BUTTON_B:--
SDL_CONTROLLER_BUTTON_X:--
SDL_CONTROLLER_BUTTON_Y:--
SDL_CONTROLLER_BUTTON_BACK:--
SDL_CONTROLLER_BUTTON_GUIDE:--
SDL_CONTROLLER_BUTTON_START:--
SDL_CONTROLLER_BUTTON_LEFTSTICK:--
SDL_CONTROLLER_BUTTON_RIGHTSTICK:--
SDL_CONTROLLER_BUTTON_LEFTSHOULDER:--
SDL_CONTROLLER_BUTTON_RIGHTSHOULDER:--
SDL_CONTROLLER_BUTTON_DPAD_UP:--
SDL_CONTROLLER_BUTTON_DPAD_DOWN:--
SDL_CONTROLLER_BUTTON_DPAD_LEFT:--
SDL_CONTROLLER_BUTTON_DPAD_RIGHT:--
SDL_CONTROLLER_BUTTON_MAX:--
.TE

.SH RELATED FUNCTIONS
\fISDL_GameControllerGetBindForButton
.br
\fISDL_GameControllerGetButton
.br
\fISDL_GameControllerGetButtonFromString
.br
\fISDL_GameControllerGetStringForButton
