.TH SDL_RectEmpty 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_RectEmpty\fR -- Function

.SH SYNOPSIS
Use this function to check whether a rectangle has no area.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
SDL_bool SDL_RectEmpty(const SDL_Rect*    r)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
r:T{
the \fBSDL_Rect\fR structure representing the rectangle to check
T}
.TE

.SH RETURN VALUE
Returns \fBSDL_TRUE\fR if the rectangle has no area or \fBSDL_FALSE\fR if it does, see \fIRemarks\fR for details.

.SH REMARKS
If the rectangle defined by \fBr\fR is NULL or has a width or height <= 0, it has no area and this function returns \fBSDL_TRUE\fR. If both width and height are > 0 the rectangle has area and this function returns \fBSDL_FALSE\fR.
