.TH SDL_JoystickNumHats 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_JoystickNumHats\fR -- Function

.SH SYNOPSIS
Use this function to get the number of POV hats on a joystick.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_JoystickNumHats(SDL_Joystick*   joystick)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
joystick:T{
an \fBSDL_Joystick\fR structure containing joystick information
T}
.TE

.SH RETURN VALUE
Returns the number of POV hats on success or a negative error code on failure; call \fBSDL_GetError()\fR for more information.

.SH RELATED FUNCTIONS
\fISDL_JoystickGetHat\fR
.br
\fISDL_JoystickOpen\fR
