.TH SDL_HINT_MOUSE_RELATIVE_MODE_WARP 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_MOUSE_RELATIVE_MODE_WARP\fR -- Hints

.SH SYNOPSIS
A hint that specifies whether relative mouse mode is implemented using mouse warping.

.SH DESCRIPTION
Values
.TP 5
.BI 0
relative mouse mode uses the raw input
.TP
.BI 1
relative mouse mose uses mouse warping

.SH DEFAULT
By default SDL will use raw input for relative mouse mode.

.SH VERSION
Available since SDL 2.0.2
