.TH SDL_ResetAssertionReport 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_ResetAssertionReport\fR -- Function

.SH SYNOPSIS
Use this function to clear the list of all assertion failures.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_ResetAssertionReport(void)
.fi
T}
.TE

.SH CODE EXAMPLES
.TS
tab(:) allbox;
a.
T{
.nf
SDL_assert(1+1 == 3);   // trigger an assertion.
printf("%p\\n", SDL_GetAssertionReport());   // not NULL.
SDL_ResetAssertionReport();
printf("%p\\n", SDL_GetAssertionReport());   // NULL
.fi
T}
.TE

.SH REMARKS
This function will clear the list of all assertions triggered up to that point. Immediately following this call, \fBSDL_GetAssertionReport()\fR will return no items. In addition, any previously-triggered assertions will be reset to a \fBtrigger_count\fR of zero, and their \fBalways_ignore\fR state will be \fBfalse\fR.

.SH RELATED FUNCTIONS
\fISDL_GetAssertionReport\fR
