.TH SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_WINDOWS_ENABLE_MESSAGELOOP\fR -- Hints

.SH Synopsis
A hint that specifies whether the windows message loop is processed by SDL.

.SH DESCRIPTION
Values
.TP 5
.BI 0
the window message loop is not run
.TP
.BI 1
the window message loop is processed in \fBSDL_PumpEvent\fR()

.SH DEFAULT
By default SDL will process the windows message loop.

.SH VERSION
Available since SDL 2.0.4

.SH NOTE
Draft
