.TH SDL_HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING\fR -- Hints

.SH Synopsis
A hint that specifies that SDL should use the old axis and button mapping for XInput devices.

.SH DESCRIPTION
Values
.TP 5
.BI 0
use the old axis and button mapping for XInput devices
.TP
.BI 1
do not use old axis and button mapping for XInput devices

.SH DEFAULT
By default SDL does not use the old axis and button mapping for XInput devices.

.SH REMARKS
This hint is for backwards compatibility only and will be removed in SDL 2.1.

.SH VERSION
Available since SDL 2.0.4

.SH NOTE
Draft
