.TH SDL_GL_UnloadLibrary 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GL_UnloadLibrary\fR -- Function

.SH SYNOPSIS
Use this function to unload the OpenGL library previously loaded by \fBSDL_GL_LoadLibrary()\fR.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_GL_UnloadLibrary(void)
.fi
T}
.TE

.SH RELATED FUNCTIONS
\fISDL_GL_LoadLibrary
