.TH SDL_EnableScreenSaver 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_EnableScreenSaver\fR -- Function

.SH SYNOPSIS
Use this function to allow the screen to be blanked by a screen saver.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_EnableScreenSaver(void)
.fi
T}
.TE

.SH VERSION
This function is available since SDL 2.0.0.

.SH RELATED FUNCTIONS
\fISDL_DisableScreenSaver
.br
\fISDL_IsScreenSaverEnabled

