.TH SDL_MessageBoxColorType 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_MessageBoxColorType\fR -- Enumerations

.SH SYNOPSIS
An enumeration of position inside the colors array of \fBSDL_MessageBoxColorScheme\fR.

.SH DESCRIPTION
Values
.TS
tab(:) allbox;
ab l.
SDL_MESSAGEBOX_COLOR_BACKGROUND:
SDL_MESSAGEBOX_COLOR_TEXT:
SDL_MESSAGEBOX_COLOR_BUTTON_BORDER:
SDL_MESSAGEBOX_COLOR_BUTTON_BACKGROUND:
SDL_MESSAGEBOX_COLOR_BUTTON_SELECTED:
SDL_MESSAGEBOX_COLOR_MAX:
.TE

.SH RELATED STRUCTURES
\fISDL_MessageBoxColorScheme
