.TH SDL_GetDisplayBounds 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GetDisplayBounds\fR -- Function

.SH SYNOPSIS
Use this function to get the desktop area represented by a display, with the primary display located at 0,0.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_GetDisplayBounds(int          displayIndex,
                         SDL_Rect*    rect)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
displayIndex:T{
the index of the display to query
T}
rect:T{
the \fBSDL_Rect\fR structure filled in with the display bounds
T}
.TE

.SH RETURN VALUE
Returns 0 on success or a negative error code on failure; call \fBSDL_GetError()\fR for more information.

.SH CODE EXAMPLES
.TS
tab(:) allbox;
a.
T{
.nf
SDL_Rect r;
if (SDL_GetDisplayBounds(0, &r) != 0)
{
  SDL_Log("SDL_GetDisplayBounds failed: %s", SDL_GetError());
  return 1;
}
.fi
T}
.TE

.SH RELATED FUNCTIONS
\fISDL_GetNumVideoDisplays
