.TH SDL_HINT_GRAB_KEYBOARD 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_GRAB_KEYBOARD\fR -- Hints

.SH SYNOPSIS
A hint that specifies whether grabbing input grabs the keyboard.

.SH DESCRIPTION
Values
.TP 5
.BI 0
grab will affect only the mouse
.TP
.BI 1
grab will affect mouse and keyboard

.SH DEFAULT
By default SDL will not grab the keyboard so system shortcuts still work.

.SH NOTE
Draft
