.TH SDL_WriteLE32 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_WriteLE32\fR -- Function

.SH SYNOPSIS
Use this function to write 32 bits in native format to a \fBSDL_RWops\fR as little-endian data.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
size_t SDL_WriteLE32(SDL_RWops*     dst,
                     Uint32         value)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
dst:T{
the stream to which data will be written
T}
value:T{
the data to be written, in native format
T}
.TE

.SH RETURN VALUE
Returns 1 on successful write, 0 on error

.SH REMARKS
SDL byteswaps the data only necessary, so the application always specifies native format, and the data written will be in little-endian format.

.SH RELATED FUNCTIONS
\fISDL_WriteBE32\fR
