.TH SDL_GetRenderTarget 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GetRenderTarget\fR -- Function

.SH SYNOPSIS
Use this function to get the current render target.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
SDL_Texture* SDL_GetRenderTarget(SDL_Renderer* renderer)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
renderer:T{
the rendering context
T}
.TE

.SH RETURN VALUE
Returns the current rendertarget or NULL for the default render target.

.SH REMARKS
The default render target is the window for which the renderer was created.

.SH RELATED FUNCTIONS
\fISDL_SetRenderTarget
