.TH SDL_JoystickClose 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_JoystickClose\fR -- Function

.SH SYNOPSIS
Use this function to close a joystick previously opened with \fBSDL_JoystickOpen()\fR.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_JoystickClose(SDL_Joystick* joystick)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
joystick:T{
an \fBSDL_Joystick\fR structure containing joystick information
T}
.TE

.SH RELATED FUNCTIONS
\fISDL_JoystickOpen
