.TH SDL_MessageBoxFlags 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_MessageBoxFlags\fR -- Enumerations

.SH SYNOPSIS
An enumeration of message box flags (e.g. if supported message box will display warning icon).

.SH DESCRIPTION
Values
.TS
tab(:) allbox;
ab l.
SDL_MESSAGEBOX_ERROR:T{
error dialog
T}
SDL_MESSAGEBOX_WARNING:T{
warning dialog
T}
SDL_MESSAGEBOX_INFORMATION:T{
informational dialog
T}
.TE

.SH RELATED STRUCTURES
\fISDL_MessageBoxData

.SH RELATED FUNCTIONS
\fISDL_ShowSimpleMessageBox
