.TH SDL_SwapLE32 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_SwapLE32\fR -- Function

.SH SYNOPSIS
Use this function to swap the byte order of a 32-bit little-endian value to native ordering.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
Uint32 SDL_SwapLE32(Uint32    x)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
x:T{
the value to be swapped
T}
.TE

.SH RETURN VALUE
Returns the native 32-bit value.

.SH RELATED FUNCTIONS
\fISDL_Swap32\fR
.br
\fISDL_SwapBE32\fR
