.TH SDL_HINT_GRAB_KEYBOARD 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_GRAB_KEYBOARD\fR -- Hints

.SH Synopsis
A hint that specifies whether grabbing input grabs the keyboard.

.SH DESCRIPTION
\fBValues
.RS 4
\fB0
\fRgrab will affect only the mouse
.br
\fB1
\fRgrab will affect mouse and keyboard
.RE

.SH DEFAULT
By default SDL will not grab the keyboard so system shortcuts still work.

.SH NOTE
Draft
