.TH SDL_HINT_ACCELEROMETER_AS_JOYSTICK 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_ACCELEROMETER_AS_JOYSTICK\fR -- Hints

.SH Synopsis
Values
.TP 5
.BI 0
list only real joysticks and accept input from them
.TP
.BI 1
list real joysticks along with the accelerometer as if it were a 3 axis joystick \fI(the default)

.SH DESCRIPTION
A hint that specifies whether the Android / iOS built-in accelerometer should be listed as a joystick device, rather than listing actual.

.PP
By default SDL will list real joysticks along with the accelerometer as if it were a 3 axis joystick.

.SH REMARKS
The hint is supported for iOS since SDL 2.0.4

.SH VERSION
Since SDL 2.0.2
