.TH SDL_LowerBlitScaled 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_LowerBlitScaled\fR -- Function

.SH SYNOPSIS
Use this function to perform low-level surface scaled blitting only.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_LowerBlitScaled(SDL_Surface*    src,
                        SDL_Rect*       srcrect,
                        SDL_Surface*    dst,
                        SDL_Rect*       dstrect)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
src:T{
the \fBSDL_Surface\fR structure to be copied from
T}
srcrect:T{
the \fBSDL_Rect\fR structure representing the rectangle to be copied
T}
dst:T{
the \fBSDL_Surface\fR structure that is the blit target
T}
dstrect:T{
the \fBSDL_Rect\fR structure representing the rectangle that is copied into
T}
.TE

.SH RETURN VALUE
Returns 0 on success or a negative error code on failure; call \fBSDL_GetError()\fR for more information.

.SH REMARKS
This is a semi-private function and it performs low-level surface blitting, assuming the input rectangle have already been clipped.

.SH RELATED FUNCTIONS
\fISDL_BlitScaled\fR
