.TH SDL_iPhoneSetEventPump 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_iPhoneSetEventPump\fR -- Function

.SH SYNOPSIS
Use this function to enable or disable the SDL event pump on Apple iOS.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_iPhoneSetEventPump(SDL_bool        enabled)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
enabled:T{
\fBSDL_TRUE\fR to enable the event pump, \fBSDL_FALSE\fR to disable it
T}
.TE

.SH REMARKS
This function is only available on Apple iOS.

This function is also accessible using the macro \fBSDL_iOSSetEventPump()\fR since SDL 2.0.4.

.SH VERSION
This function is available since SDL 2.0.0.

.SH RELATED FUNCTIONS
\fISDL_iPhoneSetAnimationCallback\fR
