.TH SDL_HINT_API_VIDEO_LAYER 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_API_VIDEO_LAYER\fR -- Hints

.SH Synopsis
A hint tha specifies which Dispmanx layer SDL should use on Rasberry Pi.

.SH DESCRIPTION
Values
.TP 5
.BI X
the Dispmanx layer to use

.SH DEFAULT
By default the Dispmanx layer is "10000".

.SH REMARKS
This is also known as Z-order. The variable can take a negative or positive value.

.SH VERSION
Available since SDL 2.0.5

.SH NOTE
Draft
