.TH SDL_GetRelativeMouseMode 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GetRelativeMouseMode\fR -- Function

.SH SYNOPSIS
Use this function to query whether relative mouse mode is enabled.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
SDL_bool SDL_GetRelativeMouseMode(void)
.fi
T}
.TE

.SH RELATED FUNCTIONS
\fISDL_SetRelativeMouseMode
