.TH SDL_HINT_VIDEO_X11_XVIDMODE 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_VIDEO_X11_XVIDMODE\fR -- Hints

.SH Synopsis
A hint that specifies whether the X11 VidMode extension should be used.

.SH DESCRIPTION
Values
.TP 5
.BI 0
disable XVidMode
.TP
.BI 1
enable XVidMode

.SH DEFAULT
By default SDL will use XVidMode if it is available.
