.TH SDL_AudioQuit 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_AudioQuit\fR -- Function

.SH SYNOPSIS
Use this function to shut down audio if you initialized it with \fBSDL_AudioInit()\fR.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_AudioQuit(void)
.fi
T}
.TE

.SH CODE EXAMPLES

.TS
tab(:) allbox;
a.
T{
.nf
int i;

for (i = 0; i < SDL_GetNumAudioDrivers(); ++i) {
  const char* driver_name = SDL_GetAudioDriver(i);
  if (SDL_AudioInit(driver_name)) {
    printf("Audio driver failed to initialize: %s\n", driver_name);
    continue;
  }
  SDL_AudioQuit();
}
.fi
T}
.TE

.SH REMARKS
This function is used internally, and should not be used unless you have a specific need to specify the audio driver you want to use. You should normally use \fBSDL_Quit()\fR or \fBSDL_QuitSubSystem()\fR.

.SH RELATED FUNCTIONS
\fISDL_AudioInit\fR
