.TH SDL_UpdateWindowSurfaceRects 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_UpdateWindowSurfaceRects\fR -- Function

.SH SYNOPSIS
Use this function to copy areas of the window surface to the screen.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_UpdateWindowSurfaceRects(SDL_Window*        window,
                                 const SDL_Rect*    rects,
                                 int                numrects)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
window:T{
the window to update
T}
rects:T{
any array of \fBSDL_Rect\fR structures representing areas of the surface to copy
T}
numrects:T{
the number of rectangles
T}
.TE

.SH RETURN VALUE
Returns 0 on success or a negative error code on failure; call \fBSDL_GetError()\fR for more information.

.SH REMARKS
This is the function you use to reflect changes to portions of the surface on the screen.

This function is equivalent to the SDL 1.2 API \fBSDL_UpdateRects()\fR.

.SH RELATED FUNCTIONS
\fISDL_GetWindowSurface\fR
.br
\fISDL_UpdateWindowSurface\fR
