.TH SDL_MouseMotionEvent 3 "2018.09.27" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_MouseMotionEvent\fR -- Structure

.SH SYNOPSIS
A structure that contains mouse motion event information.

.SH DATA FIELDS
.TS
tab(:) allbox;
a lb l.
Uint32:type:T{
the event type; \fBSDL_MOUSEMOTION\fR
T}
Uint32:timestamp:T{
timestamp of the event
T}
Uint32:windowID:T{
the window with mouse focus; if any
T}
Uint32:which:T{
the mouse instance id, or \fBSDL_TOUCH_MOUSEID; see \fIRemarks\fR for details
T}
Uint32:state:T{
the state of the button; see \fIRemarks\fR for details
T}
Sint32:x:T{
X coordinate, relative to window
T}
Sin32:y:T{
Y coordinate, relative to window
T}
Sint32:xrel:T{
relative motion in the X direction
T}
Sin32:yrel:T{
relative motion in the Y direction
T}
.TE

.SH REMARKS
\fBSDL_MouseMotionEvent\fR is a member of the \fBSDL_Event\fR union and is used when an event of type \fBSDL_MOUSEMOTION\fR is reported. You would access it through the event's \fImotion\fR field.

An \fBSDL_MOUSEMOTION\fR event occurs whenever a user moves the mouse within the application window or when \fBSDL_WarpMouseInWindow()\fR is called.

\fBstate\fR is a 32-bit button bitmask of the current button state and is the same as that returned by \fBSDL_GetMouseState()\fR. You can test different buttons by using the following masks:

.TS
tab(:) allbox;
ab.
SDL_BUTTON_LMASK
SDL_BUTTON_MMASK
SDL_BUTTON_RMASK
SDL_BUTTON_X1MASK
SDL_BUTTON_X2MASK
.TE

.PP
\fBwhich\fR may be \fBSDL_TOUCH_MOUSEID\fR, for events that were generated by a touch input device, and not a real mouse. You might want to ignore such events, if your application already handles \fBSDL_TouchFingerEvent\fR.

Relative motion is stored in \fBxrel\fR and \fByrel\fR and is relative to the last motion event. If relative mouse mode is enabled with \fBSDL_SetRelativeMouseMode()\fR, then the mouse will give relative motion events even when the cursor reaches the edge of the screen.

.SH RELATED ENUMERATIONS
\fISDL_EventType

.SH RELATED STRUCTURES
\fISDL_Event
.br
\fISDL_MouseButtonEvent
.br
\fISDL_MouseWheelEvent

.SH RELATED FUNCTIONS
\fISDL_GetMouseState
.br
\fISDL_GetRelativeMouseState
.br
\fISDL_SetRelativeMouseMode
