.TH SDL_QueryTexture 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_QueryTexture\fR -- Function

.SH SYNOPSIS
Use this function to query the attributes of a texture.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_QueryTexture(SDL_Texture*   texture,
                     Uint32*        format,
                     int*           access,
                     int*           w,
                     int*           h)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
texture:T{
the texture to query
T}
format:T{
a pointer filled in with the raw format of the texture; the actual format may differ, but pixel transfers will use this format; see \fBRemarks\fR for details
T}
access:T{
a pionter filled in with the actual access to the texture (one of the \fBSDL_TextureAccess\fR values)
T}
w:T{
a pointer filled in with the width of the texture in pixels
T}
h:T{
a pointer filled in with the height of the texture in pixels
T}
.TE

.SH RETURN VALUE
Returns 0 on success or a negative error code on failure; call \fBSDL_GetError()\fR for more information.

.SH CODE EXAMPLES
.TS
tab(:) allbox;
a.
T{
.nf
SDL_Texture*  source;

// loading etc ...

int w, h;
SDL_QueryTexture(source, NULL, NULL, &w, &h);
.fi
T}
.TE

.SH REMARKS
.TS
tab(:) allbox;
ab l.
SDL_PIXELFORMAT_UNKNOWN:
SDL_PIXELFORMAT_INDEX1LSB:
SDL_PIXELFORMAT_INDEX1MSB:
SDL_PIXELFORMAT_INDEX4LSB:
SDL_PIXELFORMAT_INDEX4MSB:
SDL_PIXELFORMAT_INDEX8:
SDL_PIXELFORMAT_RGB332:
SDL_PIXELFORMAT_RGB444:
SDL_PIXELFORMAT_RGB555:
SDL_PIXELFORMAT_BGR555:
SDL_PIXELFORMAT_ARGB4444:
SDL_PIXELFORMAT_RGBA4444:
SDL_PIXELFORMAT_ABGR4444:
SDL_PIXELFORMAT_BGRA4444:
SDL_PIXELFORMAT_ARGB1555:
SDL_PIXELFORMAT_RGBA5551:
SDL_PIXELFORMAT_ABGR1555:
SDL_PIXELFORMAT_BGRA5551:
SDL_PIXELFORMAT_RGB565:
SDL_PIXELFORMAT_BGR565:
SDL_PIXELFORMAT_RGB24:
SDL_PIXELFORMAT_BGR24:
SDL_PIXELFORMAT_RGB888:
SDL_PIXELFORMAT_RGBX8888:
SDL_PIXELFORMAT_BGR888:
SDL_PIXELFORMAT_BGRX8888:
SDL_PIXELFORMAT_ARGB8888:
SDL_PIXELFORMAT_RGBA8888:
SDL_PIXELFORMAT_ABGR8888:
SDL_PIXELFORMAT_BGRA8888:
SDL_PIXELFORMAT_ARGB2101010:
SDL_PIXELFORMAT_RGBA32:T{
alias for RGBA byte array of color data, for the current platform (>= SDL 2.0.5)
T}
SDL_PIXELFORMAT_ARGB32:T{
alias for ARGB byte array of color data, for the current platform (>= SDL 2.0.5)
T}
SDL_PIXELFORMAT_BGRA32:T{
alias for BGRA byte array of color data, for the current platform (>= SDL 2.0.5)
T}
SDL_PIXELFORMAT_ABGR32:T{
alias for ABGR byte array of color data, for the current platform (>= SDL 2.0.5)
T}
SDL_PIXELFORMAT_YV12:T{
planar mode: Y + V + U (3 planes)
T}
SDL_PIXELFORMAT_IYUV:T{
planar mode: Y + U + V (3 planes)
T}
SDL_PIXELFORMAT_YUY2:T{
packet mode: Y0 + U0 + Y1 + V0 (1 plane)
T}
SDL_PIXELFORMAT_UYVY:T{
packed mode: U0 + Y0 + V0 + Y1 (1 plane)
T}
SDL_PIXELFORMAT_YVYU:T{
packed mode: Y0 + V0 + Y1 + U0 (1 plane)
T}
SDL_PIXELFORMAT_NV12:T{
planar mode: Y + U/V interleaved (2 planes) (>= SDL 2.0.4)
T}
SDL_PIXELFORMAT_NV21:T{
planar mode: Y + V/U interleaved (2 planes) (>= SDL 2.0.4)
T}
.TE

.SH RELATED FUNCTIONS
\fISDL_CreateTexture\fR
