.TH SDL_GLattr 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GLattr\fR -- Enumerations

.SH Synopsis
An enumeration of OpenGL configuration attributes.

.SH DESCRIPTION
Values
.TS
tab(:) allbox;
ab a.
SDL_GL_RED_SIZE:T{
the minimum number of bits for the red channel of the color buffer; \fIdefaults\fR to 3
T}
SDL_GL_GREEN_SIZE:T{
the minimum number of bits for the green channel of the color buffer; \fIdefaults\fR to 3
T}
SDL_GL_BLUE_SIZE:T{
the minimum number of bits for the blue channel of the color buffer; \fIdefaults\fR to 2
T}
SDL_GL_ALPHA_SIZE:T{
the minimum number of bits for the alpha channel of the color buffer; \fdefaults\fR to 0
T}
SDL_GL_BUFFER_SIZE:T{
the minimum number of bits for frame buffer size; \fIdefaults\fR to 0
T}
SDL_GL_DOUBLEBUFFER:T{
whether the output is single or double buffered; \fIdefaults\fR to double buffering on
T}
SDL_GL_DEPTH_SIZE:T{
the minimum number of bits in the depth buffer; \fIdefaults\fR to 16
T}
SDL_GL_STENCIL_SIZE:T{
the minimum number of bits in the stencil buffer; \fIdefaults\fR to 0
T}
SDL_GL_ACCUM_RED_SIZE:T{
the minimum number of bits for the red channel of the accumulation buffer; \fIdefaults\fR to 0
T}
SDL_GL_ACCUM_GREEN_SIZE:T{
the minimum number of bits for the green channel of the accumulation buffer; \fIdefaults\fR to 0
T}
SDL_GL_ACCUM_BLUE_SIZE:T{
the minimum number of bits for the blue channel of the accumulation buffer; \fIdefaults\fR to 0
T}
SDL_GL_ACCUM_ALPHA_SIZE:T{
the minimum number of bits for the alpha channel of the accumulation buffer; \fIdefaults\fR to 0
T}
SDL_GL_STEREO:T{
whether the output is stereo 3D; \fIdefaults\fR to off
T}
SDL_GL_MULTISAMPLEBUFFERS:T{
the number of buffers used for multisample anti\-aliasing; \fIdefaults\fR to 0; see \fIRemarks\fR for details
T}
SDL_GL_MULTISAMPLESAMPLES:T{
the number of samples used around the current pixel used for multisample anti\-aliasing; \fIdefaults\fR to 0; see \fIRemarks\fR for details
T}
SDL_GL_ACCELERATED_VISUAL:T{
set to 1 to require hardware acceleration, set to 0 to force software rendering; \fIdefaults\fR to allow either
T}
SDL_GL_RETAINED_BACKING:T{
not used (deprecated)
T}
SDL_GL_CONTEXT_MAJOR_VERSION:T{
OpenGL context major version; see \fIRemarks\fR for details
T}
SDL_GL_CONTEXT_MINOR_VERSION:T{
OpenGL context minor version; see \fIRemarks\fR for details
T}
SDL_GL_CONTEXT_FLAGS:T{
some combination of 0 or more of elements of the \fBSDL_GLContextFlag\fR enumeration; \fIdefaults\fR to 0
T}
SDL_GL_CONTEXT_PROFILE_MASK:T{
type of GL context (Core, Compatibility, ES). See \fBSDL_GLprofile\fR; \fIdefaults\fR value depends on platform
T}
SDL_GL_SHARE_WITH_CURRENT_CONTEXT:T{
OpenGL context sharing; \fIdefaults\fR to 0
T}
SDL_GL_FRAMEBUFFER_SRGB_CAPABLE:T{
requests sRGB capable visual; \fIdefaults\fR to 0 (>= SDL 2.0.1)
T}
SDL_GL_CONTEXT_RELEASE_BEHAVIOR:T{
sets context the release behavior; \fIdefaults\fR to 1 (>= SDL 2.0.4)
T}
SDL_GL_CONTEXT_EGL:T{
not used (deprecated)
T}
.TE

.SH CODE EXAMPLES
.nf
SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
SDL_GL_CreateContext(window);
.fi

.SH REMARKS
While you can set most OpenGL attributes normally, the attributes listed above must be known before SDL creates the window that will be used the OpenGL context. These attributes are set and read with \fBSDL_GL_SetAttribute\fR() and \fBSDL_GL_GetAttribute\fR().
.PP
In some cases, these attributes are minimum requests; the GL does not promise to give you exactly what you asked for. It's possible to ask for a 16-bit depth buffer and get a 24-bit one instead, for example, or to ask for no stencil buffer and still have one available. Context creation should fail if the GL can't provide your requested attributes at a minimum, but you should check to see exactly what you got.
.PP
Multisample anti-aliasing (\fIhttps://en.wikipedia.org/wiki/Multisample_anti-aliasing\fR) is a type of full screen anti-aliasing. Multisampling defaults to off but can be turned on by setting \fBSDL_GL_MULTISAMPLEBUFFERS\fR to 1 and \fBSDL_GL_MULTISAMPLESAMPLES\fR to a value greater than 0. Typical values are 2 and 4.
.PP
\fBSDL_GL_CONTEXT_PROFILE_MASK\fR determines the type of context created, while both \fBSDL_GL_CONTEXT_MAJOR_VERSION\fR and \fBSDL_GL_CONTEXT_MINOR_VERSION\fR determine which version. All three attributes must be set prior to creating the first window, and in general you can't change the value of \fBSDL_GL_CONTEXT_PROFILE_MASK\fR without first destroying all windows created with the previous setting.
.PP
\fBSDL_GL_CONTEXT_RELEASE_BEHAVIOR\fR can be set to \fBSDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE\fR or \fBSDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH\fR.

.SH RELATED FUNCTIONS
\fISDL_GL_CreateContext
.br
\fISDL_GL_GetAttribute
.br
\fISDL_GL_SetAttribute
.br
