.TH SDL_HINT_XINPUT_ENABLED 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_XINPUT_ENABLED\fR -- Hints

.SH Synopsis
A hint that specifies if XInput gamepad devices are detected.

.SH DESCRIPTION
Values
.TP 5
.BI 0
disable XInput detection (only uses direct input)
.TP
.BI 1
enable XInput detection (the \fIdefault\fR)

.SH DEFAULT
By default XInput gamepad devices are detected.
