.TH SDL_BlendOperation 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_BlendOperation\fR -- Enumerations

.SH Synopsis
An enumeration of blend operations used when creating a custom blend mode with \fBSDL_ComposeCustomBlendMode\fR().

.SH DESCRIPTION
Values
.TS
tab(:) allbox;
ab a.
SDL_BLENDOPERATION_ADD:additive operation
:dst + src
SDL_BLENDOPERATION_SUBTRACT:subtractive operation
:dst - src
SDL_BLENDOPERATION_REV_SUBTRACT:reversed subtractive operation
:src - dst
SDL_BLENDOPERATION_MINIMUM:minimum operation
:min(dst, src)
SDL_BLENDOPERATION_MAXIMUM:maximum operation
:max(dst, src)
.TE

.SH REMARKS
The blend operation takes place when the calculated pixels from a drawing operation (src) and the pixels from the render target (dst) get combined. Each component (red, green, blue, and alpha) is calcuated separately. The result is then stored in the render target.
.PP
Some renderers may not support all operations. See \fBSDL_ComposeCustomBlendMode\fR() for a list of what the current renderers support.

.SH VERSION
This enumeration is available since SDL 2.0.6.

.SH RELATED ENUMERATIONS
\fISDL_BlendFactor

.SH RELATED FUNCTIONS
\fISDL_ComposeCustomBlendMode\fR, \fISDL_SetRenderDrawBlendMode\fR, \fISDL_SetTextureBlendMode
