.TH SDL_SwapFloat 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_SwapFloat\fR -- Function

.SH SYNOPSIS
Use this function to swap the byte order of a floating point value.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
float SDL_SwapFloat(float   x)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
x:T{
the value to be swapped
T}
.TE

.SH RETURN VALUE
Returns the swapped value.

.SH RELATED FUNCTIONS
\fISDL_SwapFloatBE\fR
.br
\fISDL_SwapFloatLE\fR
