.TH SDL_GetKeyboardFocus 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GetKeyboardFocus\fR -- Function

.SH SYNOPSIS
Use this function to get the window which currently has keyboard focus.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
SDL_Window* SDL_GetKeyboardFocus(void)
.fi
T}
.TE

.SH RETURN VALUE
Returns the window with keyboard focus.
