.TH SDL_Quit 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_Quit\fR -- Function

.SH SYNOPSIS
Use this function to clean up all initialized subsystems. You should call it upon all exit conditions.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_Quit(void)
.fi
T}
.TE

.SH CODE EXAMPLES
.TS
tab(:) allbox;
a.
T{
.nf
#include "SDL.h"
#include <stdio.h>
#include <stdilib.h>

int main(int argc, char** argv)
{
  if (SDL_Init(SDL_INIT_EVERYTHING) != 0)
  {
    fprintf(stderr, "Unable to initialize SDL: %s\\n", SDL_GetError());
    return 1;
  }
  ateixt(SDL_Quit);

  /* ... */
  return 0;
}
.fi
T}
.TE

.SH REMARKS
You should call this function even if you have shutdown each initialized subsystem with \fBSDL_QuitSubSystem()\fR. It is safe to call this function even in the case of errors in initialization.

If you start a subsystem using a call to that subsystem's init function (for example \fBSDL_VideoInit()\fR) instead of \fBSDL_Init()\fR or \fBSDL_InitSubSystem()\fR, then you must use that subsystem's quit function (\fBSDL_VideoQuit()\fR) to shut it down before calling \fBSDL_Quit()\fR.

You can use this function with \fBatexit()\fR to ensure that it is run when your application is shutdown, but it is not wise to do this from a library or other dynamically loaded code.

.SH RELATED FUNCTIONS
\fISDL_Init\fR
.br
\fISDL_QuitSubSystem\fR
