.TH SDL_InitSubSystem 3 "2021.08.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_InitSubSystem\fR -- Function

.SH SYNOPSIS
Compatibility function to initialize the SDL library.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_InitSubSystem(Uint32 flags)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
flags:T{
any of the flags used by \fBSDL_Init()\fR; see \fBSDL_Init\fR for details
T}
.TE

.SH RETURN VALUE
Returns 0 on success or a negative error code on failure; call \fBSDL_GetError()\fR for more information.

.SH REMARKS
In SDL2, this function and \fBSDL_Init()\fR are interchangeable.

.SH CODE EXAMPLES
.TS
tab(:) allbox;
a.
T{
.nf
/* Separating Joystick and Video initialization. */
SDL_Init(SDL_INIT_VIDEO);

SDL_Window* window = SDL_CreateWindow("A Window",
    SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480,
    SDL_WINDOW_FULLSCREEN);
SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, 0);

/* Do Some Video stuff */

/* Initialize the joystick subsystem */
SDL_InitSubSystem(SDL_INIT_JOYSTICK);

/* Do some stuff with video and joystick */

/* Shut them both down */
SDL_Quit();
.fi
T}
.TE

.SH RELATED FUNCTIONS
\fISDL_Init\fR
.br
\fISDL_Quit\fR
.br
\fISDL_QuitSubSystem\fR
