.TH SDL_GameControllerAxis 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GameControllerAxis\fR -- Enumerations

.SH SYNOPSIS
An enumeration of axes available from a controller.

.SH DESCRIPTION
Values
.TS
tab(:) allbox;
ab l.
SDL_CONTROLLER_AXIS_INVALID:--
SDL_CONTROLLER_AXIS_LEFTX:--
SDL_CONTROLLER_AXIS_LEFTY:--
SDL_CONTROLLER_AXIS_RIGHTX:--
SDL_CONTROLLER_AXIS_RIGHTY:--
SDL_CONTROLLER_AXIS_TRIGGERLEFT:--
SDL_CONTROLLER_AXIS_TRIGGERRIGHT:--
SDL_CONTROLLER_AXIS_MAX:--
.TE

.SH RELATED FUNCTIONS
\fISDL_GameControllerGetAxis
.br
\fISDL_GameControllerGetAxisFromString
.br
\fISDL_GameControllerGetBindForAxis
.br
\fISDL_GameControllerGetStringForAxis
