.TH SDL_COMPILEDVERSION 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_COMPILEDVERSION\fR -- Macro

.SH SYNOPSIS
Use this macro to get the SDL version number that you compiled against.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
SDL_COMPILEDVERSION
.fi
T}
.TE

.SH RELATED MACROS
\fISDL_VERSIONNUM
