.TH SDL_HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
SDL_HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION - Hints

.SH Synopsis
A hint that specifies the Android APK expansion main file version

.SH DESCRIPTION

\fBValues
.RS 4
\fBX
\fRthe Android APK expansion main file version (should be a string number like "1", "2", etc.)
.RE

.SH DEFAULT

By default this hint is not set.

.SH REMARKS
This hint must be set together with the hint \fISDL_HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION\fR
.PP
If both hints were set then \fISDL_RWFromFile()\fR will look into expansion files after a given relative path was not found in the internal storage and assets.
.PP
By default this hint is not set and the APK expansion files are not searched.

.SH VERSION

Available since SDL 2.0.4

.SH Note
Draft
