.TH SDL_ClearHints 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_ClearHints\fR -- Function

.SH SYNOPSIS
Use this function to clear all hints.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_ClearHints(void)
.fi
T}
.TE

.SH REMARKS
This function is automatically called during \fBSDL_Quit()\fR.
