.TH SDL_VideoQuit 3 "2021.08.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_VideoQuit\fR -- Function

.SH SYNOPSIS
Shut down the video subsystem, if initialized with \fBSDL_VideoInit()\fR.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_VideoQuit(void)
.fi
T}
.TE

.SH REMARKS
This function closes all windows, and restores the original video mode.

.SH RELATED FUNCTIONS
\fISDL_VideoInit\fR
