.TH SDL_HINT_VIDEO_X11_XINERAMA 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_VIDEO_X11_XINERAMA\fR -- Hints

.SH Synopsis
A hint that specifies whether the X11 Xinerama extension should be used.

.SH DESCRIPTION
Values
.TP 5
.BI 0
disable Xinerama
.TP
.BI 1
enable Xinerama

.SH DEFAULT
By default SDL will use Xinerama if it is available.

.SH NOTE
Draft
