.TH SDL_MinimizeWindow 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_MinimizeWindow\fR -- Function

.SH SYNOPSIS
Use this function to minimize a window to an iconic representation.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_MinimizeWindow(SDL_Window*   window)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
window:T{
the window to minimize
T}
.TE

.SH RELATED FUNCTIONS
\fISDL_MaximizeWindow\fR
.br
\fISDL_RestoreWindow\fR
