.TH SDL_FreeFormat 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_FreeFormat\fR -- Function

.SH SYNOPSIS
Use this function to free an \fBSDL_PixelFormat\fR structure allocated by \fBSDL_AllocFormat\fR.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_FreeFormat(SDL_PixelFormat* format)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
format:the \fBSDL_PixelFormat\fR structure to free
.TE

.SH RELATED FUNCTIONS
\fISDL_AllocFormat
