.TH SDL_HapticCondition 3 "2018.09.27" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HapticCondition\fR -- Structure

.SH SYNOPSIS
A structure that contains a template for a condition effect.

.SH DATA FIELDS
.TS
tab(:) allbox;
c s s.
Header
.T&
a lb l.
Uint16:type:T{
one of the effects handled by this structure; see \fIRemarks\fR for details
T}
\fBSDL_HapticDirection\fR:direction:T{
direction of the effect - not used at the moment; see \fIRemarks\fR for details
T}
.T&
c s s.
Replay
.T&
a lb l.
Uint32:length:T{
duration of the effect
T}
Uint16:delay:T{
delay before starting the effect
T}
.T&
c s s.
Trigger
.T&
a lb l.
Uint16:button:T{
button that triggers the effect
T}
Uint16:interval:T{
how soon it can be triggered again after button
T}
.T&
c s s.
Condition
.T&
a lb l.
Uint16:right_sat:T{
level when joystick is to the positive side; max 0xFFFF
T}
Uint16:left_sat:T{
level when joystick is to the negative side; max 0xFFFF
T}
Sint16:right_coeff:T{
how fast to increase the force towards the positive side
T}
Sint16:left_coeff:T{
how fast to increase the force towards the negative side
T}
Uint16:deadband:T{
size of the dead zone; max 0xFFFF: whole axis-range when 0-centered
T}
Sint16:center:T{
position of the dead zone
T}
.TE

.SH REMARKS
\fBtype\fR may be one of the following:

.TS
tab(:) allbox;
ab l.
SDL_HAPTIC_SPRING:T{
effect based on axis position
T}
SDL_HAPTIC_DAMPER:T{
effect based on axis velocity
T}
SDL_HAPTIC_INERTIA:T{
effect based on axis acceleration
T}
SDL_HAPTIC_FRICTION:T{
effect based on axis movement
T}
.TE

.PP
\fBdirection\fR is (currently) handled by condition internals instead of a direction member. The condition effect specific members have three parameters. The first refers to the X axis, the second refers to the Y axis and the third refers to the Z axis. The right terms refer to the positive side of the axis and the left terms refer to the negative side of the axis. Please refer to the \fBSDL_HapticDirection\fR diagram for which side is positive and which is negative.

.SH RELATED STRUCTURES
\fISDL_HapticDirection

.SH RELATED FUNCTIONS
\fISDL_HapticNewEffect
