.TH SDL_SetError 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_SetError\fR -- Function

.SH SYNOPSIS
Use this function to set the SDL error message.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
int SDL_SetError(const char*    fmt,
                 ...)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
fmt:T{
a \fBprintf()\fR style message format string
T}
\.\.\.:T{
additional parameters matching % tokens in the \fBfmt\fR string, if any
T}
.TE

.SH RETURN VALUE
Returns always -1.

.SH CODE EXAMPLEs
.TS
tab(:) allbox;
a.
T{
.nf
SDL_SetError("Something unexpected happened!");
.fi
T}
.TE

.TS
tab(:) allbox;
a.
T{
.nf
int errorCode = 0;
...
errorCode = -37;
...
if (errorCode < 0)
    SDL_SetError("Something unexpected happened: Error Code %d", errorCode);
.fi
T}
.TE

.SH REMARKS
Calling this function will replace any previous error message that was set.

.SH RELATED FUNCTIONS
\fISDL_ClearError\fR
.br
\fISDL_GetError\fR
