.TH SDL_MessageBoxButtonFlags 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_MessageBoxButtonFlags\fR -- Enumerations

.SH SYNOPSIS
An enumeration of flags for \fBSDL_MessageBoxButtonData\fR.

.SH DESCRIPTION
Values
.TS
tab(:) allbox;
ab l.
SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT:T{
marks the default button when return is hit
T}
SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT:T{
marks the default button when escape is hit
T}
.TE

.SH RELATED STRUCTURES
\fISDL_MessageBoxButtonData
