.TH SDL_Renderer 3 "2018.09.27" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_Renderer\fR -- Structure

.SH SYNOPSIS
A structure that contains a rendering state.

.SH RELATED FUNCTIONS
\fISDL_CreateRenderer
.br
\fISDL_CreateSoftwareRenderer
.br
\fISDL_CreateTexture
.br
\fISDL_CreateTextureFromSurface
.br
\fISDL_CreateWindowAndRenderer
.br
\fISDL_DestroyRenderer
.br
\fISDL_GetRenderDrawBlendMode
.br
\fISDL_GetRenderDrawColor
.br
\fISDL_GetRendererInfo
.br
\fISDL_GetRendererOutputSize
.br
\fISDL_GetRenderTarget
.br
\fISDL_RenderClear
.br
\fISDL_RenderCopy
.br
\fISDL_RenderCopyEx
.br
\fISDL_RenderDrawLine
.br
\fISDL_RenderDrawLines
.br
\fISDL_RenderDrawPoint
.br
\fISDL_RenderDrawPoints
.br
\fISDL_RenderDrawRect
.br
\fISDL_RenderDrawRects
.br
\fISDL_RenderFillRect
.br
\fISDL_RenderFillRects
.br
\fISDL_RenderGetClipRect
.br
\fISDL_RenderGetIntegerScale
.br
\fISDL_RenderGetLogicalSize
.br
\fISDL_RenderGetScale
.br
\fISDL_RenderGetViewport
.br
\fISDL_RenderIsClipEnabled
.br
\fISDL_RenderPresent
.br
\fISDL_RenderReadPixels
.br
\fISDL_RenderSetClipRect
.br
\fISDL_RenderSetIntegerScale
.br
\fISDL_RenderSetLogicalSize
.br
\fISDL_RenderSetScale
.br
\fISDL_RenderSetViewport
.br
\fISDL_RenderTargetSupported
.br
\fISDL_SetRenderDrawBlendMode
.br
\fISDL_SetRenderDrawColor
.br
\fISDL_SetRenderTarget
