.TH SDL_MaximizeWindow 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_MaximizeWindow\fR -- Function

.SH SYNOPSIS
Use this function to make a window as large as possible.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_MaximizeWindow(SDL_Window*   window)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
window:T{
the window to maximize
T}
.TE

.SH RELATED FUNCTIONS
\fISDL_MinimizeWindow\fR
.br
\fISDL_RestoreWindow\fR
