.TH SDL_MessageBoxColor 3 "2018.09.27" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_MessageBoxColor\fR -- Structure

.SH SYNOPSIS
A structure that contains RGB value used in an \fBSDL_MessageBoxColorScheme\fR.

.SH DATA FIELDS
.TS
tab(:) allbox;
a lb l.
Uint8:r:T{
the red component in the range 0-255
T}
Uint8:g:T{
the green component in the range 0-255
T}
Uint8:b:T{
the blue component in the range 0-255
T}
.TE

.SH RELATED STRUCTURES
\fISDL_MessageBoxColorScheme
