.TH SDL_JoyAxisEvent 3 "2018.09.27" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_JoyAxisEvent\fR -- Structure

.SH SYNOPSIS
A structure that contains joystick axis motion event information.

.SH DATA FIELDS
.TS
tab(:) allbox;
a lb l.
Uint32:type:T{
\fBSDL_JOYAXISMOTION\fR
T}
Uint32:timestamp:T{
timestamp of the event
T}
\fBSDL_JoystickID\fR:which:T{
the instance id of the joystick that reported the event
T}
Uint8:axis:T{
the index of the axis that changed
T}
Sint16:value:T{
the current position of the axis (range: -32768 to 32767)
T}
.TE

.SH REMARKS
\fBSDL_JoyAxisEvent\fR is a member of the \fBSDL_Event\fR union and is used when an event of type \fBSDL_JOYAXISMOTION\fR is reported. You would access it through the event's \fIjaxis\fR field.

An \fBSDL_JOYAXISMOTION\fR event occurs whenever a user moves an axis on the joystick.

.SH RELATED ENUMERATIONS
\fISDL_EventType

.SH RELATED STRUCTURES
\fISDL_Event
.br
\fISDL_JoyBallEvent
.br
\fISDL_JoyButtonEvent
.br
\fISDL_JoyHatEvent

.SH RELATED FUNCTIONS
\fISDL_JoystickEventState
.br
\fISDL_JoystickGetAxis
