.TH SDL_HasMMX 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HasMMX\fR -- Function

.SH SYNOPSIS
Use this function to determine whether the CPU has MMX features.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
SDL_bool SDL_HasMMX(void)
.fi
T}
.TE

.SH RETURN VALUE
Returns \fBSDL_TRUE\fR if the CPU has MMX features or \fBSDL_FALSE\fR if not.

.SH RELATED FUNCTIONS
\fISDL_Has3DNow\fR
.br
\fISDL_HasAltiVec\fR
.br
\fISDL_HasAVX\fR
.br
\fISDL_HasAVX2\fR
.br
\fISDL_HasRDTSC\fR
.br
\fISDL_HasSSE\fR
.br
\fISDL_HasSSE2\fR
.br
\fISDL_HasSSE3\fR
.br
\fISDL_HasSSE41\fR
.br
\fISDL_HasSSE42\fR
