.TH SDL_GetMouseFocus 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GetMouseFocus\fR -- Function

.SH SYNOPSIS
Use this function to get the window currently has mouse focus.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
SDL_Window* SDL_GetMouseFocus(void)
.fi
T}
.TE

.SH RETURN VALUE
Returns the window with mouse focus.
