.TH SDL_RaiseWindow 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_RaiseWindow\fR -- Function

.SH SYNOPSIS
Use this function to raise a window above other windows and set the input focus.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_RaiseWindow(SDL_Window*    window)
.fi
T}
.TE

.SH FUNCTION PARAMETERS
.TS
tab(:) allbox;
ab l.
window:T{
the window to raise
T}
.TE
