.TH SDL_JoyHatEvent 3 "2018.09.27" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_JoyHatEvent\fR -- Structure

.SH SYNOPSIS
A structure that contains joystick hat position change event information.

.SH DATA FIELDS
.TS
tab(:) allbox;
a lb l.
Uint32:type:T{
\fBSDL_JOYHATMOTION\fR
T}
Uint32:timestamp:T{
timestamp of the event
T}
\fBSDL_JoystickID\fR:which:T{
the instance id of the joystick that reported the event
T}
Uint8:hat:T{
the index of the hat that changed
T}
Uint8:value:T{
the new position of the hat; see \fIRemarks\fR for details
T}
.TE

.SH REMARKS
\fBSDL_JoyHatEvent\fR is a member of the \fBSDL_Event\fR union and is used when an event of type \fBSDL_JOYHATMOTION\fR is reportedl. You would access it through the event's \fIjhat\fR field.

An \fBSDL_JOYHATMOTION\fR event occurs whenever a user moves a hat on the joystickk.

\fBvalue\fR may be one of the following:

.TS
tab(:) allbox;
ab lb lb.
SDL_HAT_LEFTUP:SDL_HAT_UP:SDL_HAT_RIGHTUP
SDL_HAT_LEFT:SDL_HAT_CENTERED:SDL_HAT_RIGHT
SDL_HAT_LEFTDOWN:SDL_HAT_DOWN:SDL_HAT_RIGHTDOWN
.TE

.PP
Note that zero means the POV is centered.

.SH RELATED ENUMERATIONS
\fISDL_EventType

.SH RELATAED STRUCTURES
\fISDL_Event
.br
\fISDL_JoyAxisEvent
.br
\fISDL_JoyBallEvent
.br
\fISDL_JoyButtonEvent

.SH RELATED FUNCTIONS
\fISDL_JoystickEventState
.br
\fISDL_JoystickGetHat
