.TH SDL_GL_ResetAttributes 3 "2018.10.07" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_GL_ResetAttributes\fR -- Function

.SH SYNOPSIS
Use this function to reset all previously set OpenGL context attributes to their default values.

.SH SYNTAX
.TS
tab(:) allbox;
a.
T{
.nf
void SDL_GL_ResetAttributes(void)
.fi
T}
.TE

.SH VERSION
This function is available since SDL 2.0.2.

.SH RELATED FUNCTIONS
\fISDL_GL_GetAttribute
.br
\fISDL_GL_SetAttribute
