.TH SDL_HINT_RENDER_SCALE_QUALITY 3 "2018.08.14" "https://github.com/haxpor/sdl2-manpage" "SDL2"
.SH NAME
\fBSDL_HINT_RENDER_SCALE_QUALITY\fR -- Hints

.SH SYNOPSIS
A hint that specifies scaling quality.

.SH DESCRIPTION
Values
.TP 20
.BI "0 or nearest"
nearest pixel sampling
.TP
.BI "1 or linear"
linear filtering (supported by OpenGL and Direct3D)
.TP
.BI "2 or best"
anisotropic filtering (supported by Direct3D)

.SH DEFAULT
By default neartest pixel sampling is used.

.SH REMARKS
This hint is checked when a texture is created and it affects scaling when copying that texture.
